cabal-version:       2.2
name:                ivory-tower-helloworld
version:             0.1.0.0
synopsis:            Collection of example applications for Ivory Tower and STM32
license:             BSD-3-Clause
author:              Sorki
maintainer:          srk@48.io
copyright:           2020 Richard Marko
category:            Embedded
build-type:          Simple

library
  hs-source-dirs:      src
  exposed-modules:
                       Hello.Tests.Blink
                       Hello.Tests.Platforms
                       Hello.Tests.Platforms.Types
                       Hello.Tests.Platforms.F4DISCO
                       Hello.Tests.SimpleBlink
                       Hello.Tests.Sk8r
                       Hello.Tests.Mpu6050Tower
                       Hello.Tests.WhoIs6050
                       Hello.Tests.FlightTrackerTower
                       Hello.Tests.MadgwickTower

  build-depends:       base
                     , ivory
                     , ivory-bsp-stm32
                     , ivory-hw
                     , ivory-tower-base
                     , tower
                     , tower-config
                     , tower-hal
                     , tower-freertos-stm32

  default-language:    Haskell2010
  ghc-options:         -Wall -Wunused-packages

executable blink-test-gen
  main-is:             Blink.hs
  hs-source-dirs:      test
  build-depends:       base
                     , ivory-tower-helloworld
  ghc-options:         -Wall

executable simpleblink-test-gen
  main-is:             SimpleBlink.hs
  hs-source-dirs:      test
  build-depends:       base
                     , ivory-tower-helloworld
  ghc-options:         -Wall

executable sk8r-test-gen
  main-is:             sk8r.hs
  hs-source-dirs:      test
  build-depends:       base
                     , ivory-tower-helloworld
  ghc-options:         -Wall

executable whois6050-test-gen
  main-is:             whoIs6050.hs
  hs-source-dirs:      test
  build-depends:       base
                     , ivory-tower-helloworld
  ghc-options:         -Wall